fos_rest:
  service:
    serializer: fos_rest.serializer.symfony
  param_fetcher_listener:  true
  body_listener: true
  body_converter:
    enabled: true
    validate: true
    validation_errors_argument: validationErrors
  allowed_methods_listener:  true
  view:
    view_response_listener:  'force'
    formats:
      json: true
  format_listener:
    rules:
      - { path: ^/api, fallback_format: json, priorities: [ json ] }
      - { path: ^/, fallback_format: html, priorities: [ html ] }