nelmio_api_doc:
    documentation:
        #        schemes: [http, https]
        info:
            title: Rent API
            description: Symfony JWT API docs
            version: 1.0.0
        security:
            - Bearer: []
        tags:
            - name: "Rent"
              description: "Rent endpoints"
            - name: "Renter"
              description: "Renter endpoints"
            - name: "Book"
              description: "Book endpoints"
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/docs|/contexts|/{index}|/doc|.json$) # Accepts routes under /api except